server:
  port: 8082
spring:
  mail:
    #   邮件服务器地址
    host: smtp.126.com
    #    协议
    protocol: smtp
    #    编码格式
    default-encoding: UTF-8
    #    授权码
    password: RDIHVZUYQTKHENFW
    #    发送者邮箱地址
    username: haopengfei91@126.com
    #    端口
    port: 25

  rabbitmq:
    #    用户名
    username: guest
    #    密码
    password: guest
    #    服务器地址
    host: 127.0.0.1
    #    端口
    port: 5672